### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by vheesen** [mhardcastle/radioflux#9]
Hi Martin,

I get the following error message, when using radioflux.py as a stand-alone version.

stnv047@hspc50:~/data/sfr/n5055$ radioflux.py -f n5055_flux.ds9 n5055_lofar_144mhz_18arcs.fits
Traceback (most recent call last):
  File "/home/hslxrsrv3/stnv047/bin/radioflux.py", line 306, in <module>
    flux_for_files(args.files,args.fgr,args.bgr,args.indiv,args.bgsub,verbose=args.verbose)
  File "/home/hslxrsrv3/stnv047/bin/radioflux.py", line 279, in flux_for_files
    fg_ir=pyregion.open(fgr).as_imagecoord(rm.headers[0])
  File "/home/hslxrsrv3/stnv047/.local/lib/python2.7/site-packages/pyregion/core.py", line 70, in as_imagecoord
    shape_list, comment_list = zip(*list(r))
  File "/home/hslxrsrv3/stnv047/.local/lib/python2.7/site-packages/pyregion/ds9_region_parser.py", line 187, in sky_to_image
    new_coords = convert_to_imagecoord(shape, header)
  File "/home/hslxrsrv3/stnv047/.local/lib/python2.7/site-packages/pyregion/wcs_converter.py", line 109, in convert_to_imagecoord
    header)
  File "/home/hslxrsrv3/stnv047/.local/lib/python2.7/site-packages/pyregion/wcs_helper.py", line 26, in _estimate_angle
    y_axis_rot = _calculate_rotation_angle(reg_coordinate_frame, header)
  File "/home/hslxrsrv3/stnv047/.local/lib/python2.7/site-packages/pyregion/wcs_helper.py", line 65, in _calculate_rotation_angle
    header['NAXIS1'] / 2,
  File "/home/hslxrsrv3/stnv047/.local/lib/python2.7/site-packages/astropy/io/fits/header.py", line 150, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "/home/hslxrsrv3/stnv047/.local/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1674, in _cardindex
    raise KeyError("Keyword {!r} not found.".format(keyword))
KeyError: "Keyword 'NAXIS1' not found."

I have installed it with pip.

Cheers,
Volker

**Comment by mhardcastle** [comment]
Hi Volker,as you can see this is a pyregion error, but I'm surprised to see an error like this since the code works with most types of radio maps. If you can send me the map by e-mail or point me to a link I will investigate for you. Are you using up-to-date versions of pyregion and astropy?

**Comment by mhardcastle** [comment]
I can't reproduce this with the map you sent me (which looks fine) and any combination of versions of radioflux, pyregion and astropy that I have access to.

```
/usr/local/lib/python2.7/dist-packages/radioflux/radioflux.py -f ds9.reg n5055_lofar_144mhz_18arcs.fits 
n5055_lofar_144mhz_18arcs.fits  1.437e+08    2.09665
```

**Comment by vheesen** [comment]
Would radioflux work on python 3.6 or is this python 2.7? Thanks!

**Comment by mhardcastle** [comment]
It's 2.7 only at the moment I'm afraid. It would be easy to convert.

**Comment by mhardcastle** [comment]
A long time later, but I have finally tracked this down in a python3 install (with help from Manu) and fixed it. Going to open a new issue for the general python2/3 problem.
